package fr.ecp.is1220.projetc.part2.simulation;

public enum EventsType {
	ARRL1, ARRL2, ARRL3, ARRL4, ARRL5, REGISTURGENT, REGISTNONURGENT, VISIT, TRANSPORTATION, RADIOGRAPHY, SCAN, BLOODTEST, MRI, XRAY, ENDEVENT, FREENURSE, FREEPHYSICIAN, FREETRANSPORTER
}
