package fr.ecp.is1220.projet.part1.core;

public enum ResourcesType {
	BOXROOM, SHOCKROOM, BLOODTEST, SCAN, XRAY, CONSULTATIONSERVICE, MRI, RADIOGRAPHY, STRECHER, WAITINGROOM, NURSE, PHYSICIAN, TRANSPORTER

}
